export const AUTH_STACK_SCREEN = {
  SINGiN: 'SIGNIN',
  REGISTER: 'REGISTER',
};
export const BOTTOM_TAB_SCREEN = {
  HOME: 'HOME',
  JOINUS: 'JOINUS',
  EXPLORE: 'EXPLORE',
  PROFILE: 'PROFILE',
};
export const STACK_SCREEN = {
  BOTTOM_TAB: 'BOTTOM_TABS',
};
